language: php
sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 5.5
    - php: 5.4
    - php: 5.3

before_script:
  - composer install --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry ./vendor/bin/coveralls