language: php
sudo: false

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 5.6

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry ./vendor/bin/coveralls